name: Launchable Demo

on:
  pull_request:
  workflow_dispatch:

env:
  SMART_TESTS_ORGANIZATION: "launchable-demo"
  SMART_TESTS_WORKSPACE: "hands-on-lab"

jobs:
  PreMergeTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Smart Tests CLI
        run: pip install --user --upgrade smart-tests-cli~=2.0 
      - name: Smart Tests verify
        run: smart-tests verify        
      - name: Smart Tests record build
        run: smart-tests record build --build ${{ github.run_id }}        
      - name: Compile
        run: mvn compile
      - name: Smart Tests subset
        run: |
          smart-tests record session --build ${{ github.run_id }} --observation --test-suite unit-test > session.txt
          smart-tests subset --session @session.txt --target 50% maven src/test/java > smart-tests-subset.txt
          cat smart-tests-subset.txt        
      - name: Test
        run: mvn test
