name: Launchable Demo

on:
  pull_request:
  workflow_dispatch:

env:
  SMART_TESTS_ORGANIZATION: "launchable-demo"
  SMART_TESTS_WORKSPACE: "hands-on-lab"

jobs:
  PreMergeTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn test
